name = "nxtjobassessment" 
compatibility_date = "2025-01-19"

main = "./dist/server.js" 

account_id = "354bd4f9200b361f34141147498e1bba"

[build]
command = "npm run build"

[experimental]
nodejs_compat = true